---
- name: Añadir el repositorio apt de Docker (formato DEB822)
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
    suites: "{{ ansible_facts['distribution_release'] | lower }}"
    components: stable
    architectures: "{{ ansible_facts['architecture'] | regex_replace('x86_64', 'amd64') }}"
    signed_by: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    state: present

- name: Actualizar el índice de paquetes
  ansible.builtin.apt:
    update_cache: true

- name: Instalar Docker y sus dependencias
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Arrancar el servicio Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Añadir el usuario debian al grupo docker
  ansible.builtin.user:
    name: debian
    groups: docker
    append: true
