- name: Instalar los paquetes necesarios para que apt funcione sobre HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ca-certificates
      - curl

- name: Descargar la clave de firma de paquetes de Docker
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Obtener la arquitectura del sistema
  shell: dpkg --print-architecture
  register: debian_arch

- name: Añadir el repositorio apt para la versión estable
  apt_repository:
    repo: deb [arch={{ debian_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Instalar Docker y sus dependencias
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Arrancar el servicio Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Añadir el usuario debian al grupo docker
  ansible.builtin.user:
    name: debian
    groups: docker
    append: yes
