---
- name: Comprobar los hosts disponibles
  hosts: all
  gather_facts: no
  tasks:
    - command: timeout 20 sh -c 'until nc -z $0 $1; do sleep 1; done' {{ inventory_hostname }} 22
      delegate_to: localhost
      register: ping_result
      ignore_errors: yes
    - group_by: key=reachable
      when: ping_result is success

- name: Instalar Portainer
  hosts: reachable
  vars:
    ansible_python_interpreter: auto_silent
  gather_facts: yes
  become: true
  tasks:
    - name: Instalar Portainer
      shell: |
        docker volume create portainer_data
        docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v portainer_data:/data \
          portainer/portainer-ce:sts
