---
- name: Comprobar los hosts disponibles
  hosts: all
  gather_facts: no
  tasks:
    - command: timeout 20 sh -c 'until nc -z $0 $1; do sleep 1; done' {{ inventory_hostname }} 22
      delegate_to: localhost
      register: ping_result
      ignore_errors: yes
    - group_by: key=reachable
      when: ping_result is success

- name: Instalar Portainer
  hosts: reachable
  vars:
    ansible_python_interpreter: auto_silent
  gather_facts: yes
  roles:
    - portainer
