- name: Añadir el grupo ubuntu con GID 1000
  group:
    name: ubuntu
    gid: 1000
    state: present

- name: Añadir el usuario ubuntu con UID 1000
  ansible.builtin.user:
    name: ubuntu
    shell: /bin/bash
    uid: 1000
    group: ubuntu
    groups: docker
    append: yes

- name: Permitir sudo sin contraseña
  copy:
    content: 'ubuntu ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/ubuntu_nopasswd
    mode: 0440

- name: Crear el directorio .ssh del usuario ubuntu
  file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Copiar el fichero authorized_keys del root a ubuntu
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    dest: /home/ubuntu/.ssh/authorized_keys
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0400'
